spring:
  application:
    name: platform

  datasource:
    url: jdbc:mysql://localhost:3306/pdf2data_db?createDatabaseIfNotExist=true
    username: root
    password: vedant123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/pdf2data_nosql

gemini:
  api:
    key: AQ.Ab8RN6KuVgqE9JRyVI1aWsw2N-ZPMZsQBQWas5jrkt8F-jqdVg
    model: gemini-2.5-flash


server:
  port: 8080